from random import choice
from random import seed
from time import sleep

def philadelphia_man(adjectives, verbs, subjects, action):
    seed()
    adjective = choice(adjectives)
    seed()
    verb = choice(verbs)
    seed()
    subject = choice(subjects)
    seed()
    action = choice(action)
    if action != "":
        print "%s Philadelphia man %s %s then %s." % (adjective, verb, subject, action)
    else:
        print "%s Philadelphia man %s %s." % (adjective, verb, subject)


def main():
    adjectives = ["Irate", "Timid", "Postmodern", "Depressed", "Flummoxed", "Drunk", "Bespectacled", "Leery", "Squeemish", "Hateful", "Deeply punchable", "Naked", "Cowardly", "Enraged", "Confused", "Perplexed", "Bored", "Exhausted", "Drunk", "Inebriated", "Plastered", "Sky high", "Intoxicated", "Indisposed", "Foolish", "Dull", "Sad", "Slow", "Inept", "Surburban", "Middle-aged", "Unemployed", "Terrified", "Foul-smelling", "Hungry", "Barking", "Thirsty", "Giant", "Elderly", "Indecent", "Constipated", "Clinically insane", "Ranting", "Dim", "Confused", "Unkind", "Filthy", "Hoagie-mouthed", "Bleeding",  "Sleep-walking", "One-legged", "Incomprehensible", "Racist", "Homophobic", "Vomitting", "Bearded", "Slovenly", "Unwell", "Bedridden", "Quadripalegic", "Obsessive-compulsive", "Trusting", "Knife-weilding", "Disappointed", "Sweatpants-wearing", "Hoodie-wearing", "Meth-abusing", "Triumphant", "Hooded", "Unknown", "Rejected", "Sadistic", "Masochistic", "Deeply ashamed", "Slurring", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",]
    verbs = ["hits", "destroys", "maims", "forgets", "punches", "kicks", "licks", "envelopes", "screams at", "attempts to marry", "violates", "crushes", "breaks", "paints", "hides", "steals", "redecorates", "attempts to eat", "burns", "weeps upon", "sideswipes", "contemplates", "devours", "swindles", "replaces", "arouses", "removes", "freezes", "kisses", "slaps", "remembers", "unleashes", "escapes", "serenades", "spies on", "shoots", "enthusiastically sniffs", "forms religion surrounding", "gets trapped by", "is killed by", "impersonates", "dresses up as", "attempts to replace", "robs", "burgles", "murders", "steals", "loots", "defecates upon", "forcefully massages", "totals", "attempts to mesmerize", "willfilly disobeys", "disembowels", "drains blood from", "accidentally ingests", "overturns", "razes", "seduces", "suggestively rubs", "rides", "fails to steal", "fails to impress", "mounts", "attempts to eat", "sleeps through", "accidentally injests", "injests",  "sexually harasses", "gets fired from", "performs CPR on", "gets in an argument with", "incapacitates", "ties up", "verbally abuses", "elopes with",]
    subjects = ["his car", "his neighbor's cat", "Michael Nutter", "John Street", "Sylvester Stallone", "Ed Rendell", "midsize sedan", "80 year-old man", "escaped mountain lion from the Philadelphia Zoo", "the Liberty Bell", "the Rocky statue", "a dozen pretzels", "a cheesesteak", "rolls from Sarcone's", "Cheeze Wiz", "PPA employee", "city councilman", "the LOVE statue", "the Clothespin", "man asking for 38 cents", "passersby", "Club Voyeur", "scrapple", "Reading Terminal Market", "medical oddities","shopping cart", "Chinatown", "ESPO","Mural Arts", "elevator shaft", "McGlinchey's", "Segway scooter", "UPenn", "City Hall", "Ben Franklin's House", "Ben Franklin's Post Office", "Ben Franklin's Fire Department", "The Barnes Foundation", "down the shore", "man dressed as Kobe Bryant", "the Wannamaker organ", "M. Night Shamalan", "Meek Mill", "Will Smith", "Boyz II Men", "Tastykake", "Middle school performance of Henry VIII", "The Roots", "?Questlove", "Philadelphia Creamcheese", "Philadelphia Orchestra", "Phillies", "Eagles", "newly formed sinkhole", "Amish quilt", "76ers", "violent Phillies fans", "Flyers", "Wawa", "UArts", "bologna bikini", "Boy Meets World theme wedding", "a 6 gallon tub of cheese wiz", "personal lubricant", "It's Always Sunny DVD collection", "civil war reenactors", "bike punk", "Graduate Hospital", "Fairmount park statue", "polluted fish", "the PPA", "South Street"]
    actions = ["flees", "commits arson", "removes clothing", "claims innocence", "cries openly", "converts to Father Divine's Peace Mission Movement", "pukes cheese wiz", "smashes television", "cries about The Phillies", "buys a hot dog", "recants", "falls asleep", "vomits", "infiltrates The Philadelphia Zoo", "curses Comcast", "is able to recount all 7 Philadelphia sister cities", "insists on calling Jefferson Station-Market East", "falls asleep at the Greyhound Station", "slashes tires", "uncovers lost tokens in couch","flees on horseback", "flees in cop car", "piggy back rides police captain", "wins the lottery", "drops water ice", "dies from heart attack", "cries", "vanishes into the night", "watches cat", "tattoos own head", "goes to McDonalds", "fakes own death", "wins Wing Bowl contest", "trashes bar", "walks away bitter for it", "kills coyote", "marries Phillie Phanatic", "creates children's TV show", "drowns in Delaware", "gets lost in King Of Prussia", "finds the King Of Prussia", "loses parking spot", "double parks car overnight", "loses child", "graduates high school", "huffs cheese wiz", "writes novel about it", "urinates uncontrollably", "defecates uncontrollably", "forgets how to speak", "takes vow of silence", "attempts to vote twice", "attempts to vote for Frank Rizzo", "forgets about Northeast Philly", "accidentally drives to Camden", "falls asleep on the El", "spends night in Fairmount Park", "dies in sweatpants", "embraces sweatpants", "wears pajamas at work", "steals a bicycle", "quietly pukes", "is never seen again", "demands to see Frank Rizzo", "ignores parking ticket", "loses at Three Lo", "gets lost in the Northeast", "sues The Barnes Foundation", "slurps water ice", "tags train car", "can't find the airport", "visits traffic court", "talks his way out of ticket", "mispronounces Yuengling", "skinny dips in Schuylkill", "delivers impromptu yet inspiring speech", "eats a pretzel dog", "arouses public suspicion", "crashes into trolley", "crashes bike", "crashes forklift", "murders neighbor dog", "changes last name to Rizzo", "gets Phillies tattoo", "steals pretzel from child", "has trouble ordering at Wawa", "steals Wawa hoagie", "plots own death", "visits Philadelphia Museum of Art", "cackles maniacally", "drinks gasoline", "", "", "", "", "", "", "", "", "", "",]

    while(1):
        philadelphia_man(adjectives, verbs, subjects, actions)
        sleep(4)
if __name__ == "__main__":
    main()


